batch_size: 64
corpus_name: childes-20180319
dropout_prob: 0
embed_init_range: 0.1
embed_size: 200
grad_clip: null
job_name: null
learning_rate:
- 0.01
- 1.0
- 10
num_epochs: 20
num_eval_steps: 1000
num_layers: 1
num_steps: 7
num_vocab: 16384
param_name: param_4
rnn_type: srn
shuffle_per_epoch: true
train_percent: 0.9
